// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythicNexus.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MythicNexus.Api.src.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MythicNexusDbContext))]
    [Migration("20260514125049_DomainFoundationLoreGraph")]
    partial class DomainFoundationLoreGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreEntryTags", b =>
                {
                    b.Property<Guid>("LoreEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("LoreEntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LoreEntryTags", (string)null);
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .HasColumnType("text");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.LoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CampaignId", "Slug")
                        .IsUnique();

                    b.ToTable("LoreEntries");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.LoreRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("SourceLoreEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetLoreEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceLoreEntryId");

                    b.HasIndex("TargetLoreEntryId");

                    b.HasIndex("CampaignId", "SourceLoreEntryId", "TargetLoreEntryId", "RelationType")
                        .IsUnique();

                    b.ToTable("LoreRelations");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoreEntryTags", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.LoreEntry", null)
                        .WithMany()
                        .HasForeignKey("LoreEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythicNexus.Api.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.User", "Owner")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Character", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.LoreEntry", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.Campaign", "Campaign")
                        .WithMany("LoreEntries")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythicNexus.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany("AuthoredLoreEntries")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.LoreRelation", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.Campaign", "Campaign")
                        .WithMany("LoreRelations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythicNexus.Api.Domain.Entities.LoreEntry", "Source")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceLoreEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythicNexus.Api.Domain.Entities.LoreEntry", "Target")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetLoreEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Tag", b =>
                {
                    b.HasOne("MythicNexus.Api.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Tags")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("LoreEntries");

                    b.Navigation("LoreRelations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.LoreEntry", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");
                });

            modelBuilder.Entity("MythicNexus.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthoredLoreEntries");

                    b.Navigation("OwnedCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
